export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT = 'LOGOUT';

export const ADDTOCART = 'ADDTOCART';
export const DECREASEQUANTITY = 'DECREASEQUANTITY'
export const INCREASEQUANTITY = 'INCREASEQUANTITY'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
export const SET_MESSAGE = 'SET_MESSAGE'